In [3]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

In [5]:
from sklearn.datasets import load_wine
dataset = load_wine()

**TO** DO: Display dataset.keys() and the elements of dataset.

In [15]:
print(dataset.keys())


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [14]:
print(dataset.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [11]:
print(dataset.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [10]:
print(dataset.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [12]:
print(dataset.target_names)

['class_0' 'class_1' 'class_2']


In [13]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.data, dataset.target,random_state=0)
print('X_train.shape = ',X_train.shape)
print('y_train.shape = ',y_train.shape)
print('X_test.shape = ',X_test.shape)
print('y_train.shape = ',y_test.shape)

X_train.shape =  (133, 13)
y_train.shape =  (133,)
X_test.shape =  (45, 13)
y_train.shape =  (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


In [50]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train,y_train)
print("train score =",lr.score(X_train, y_train))
print("test score: =",lr.score(X_test, y_test)) 

train score = 0.9924812030075187
test score: = 0.9333333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

In [51]:
W_lr = lr.coef_
b_lr = lr.intercept_
print('W_lr = ',W_lr)
print('b_lr = ',b_lr)

W_lr =  [[-1.32186429e-01  3.23965050e-01  1.84092284e-01 -2.58932260e-01
  -3.55944236e-02  2.38697315e-01  5.82114322e-01 -2.22946486e-02
   9.92276027e-02  1.09948852e-01 -1.73973402e-02  4.10341111e-01
   8.36031752e-03]
 [ 5.99095455e-01 -7.17070268e-01 -2.00230225e-01  2.11071050e-01
  -1.04352065e-02  2.06746427e-01  3.95799510e-01  1.36191938e-02
   3.85959371e-01 -1.24982865e+00  2.65765529e-01  4.38399876e-01
  -8.01466640e-03]
 [-4.66909026e-01  3.93105218e-01  1.61379407e-02  4.78612099e-02
   4.60296301e-02 -4.45443742e-01 -9.77913832e-01  8.67545481e-03
  -4.85186974e-01  1.13987979e+00 -2.48368189e-01 -8.48740987e-01
  -3.45651121e-04]]
b_lr =  [-0.04937168  0.10908187 -0.05971019]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

In [53]:
from sklearn.svm import LinearSVC
svc = LinearSVC().fit(X_train,y_train)
print('train score = ',svc.score(X_train,y_train))
print('test score = ',svc.score(X_test,y_test))


train score =  0.7518796992481203
test score =  0.8444444444444444


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

In [54]:
W_svc = svc.coef_
b_svc = svc.intercept_
print('W_svc = ',W_svc)
print('b_svc = ',b_svc)

W_svc =  [[-2.51905404e-02 -1.68063024e-03 -7.48813024e-04 -1.02000228e-01
  -1.02680908e-02  1.02932596e-02  3.06351143e-02 -3.84655904e-03
   7.15768285e-03 -1.78027213e-02 -8.02613228e-04  1.71451236e-02
   3.82421988e-03]
 [ 4.64890910e-02 -8.01446165e-02 -6.30351889e-03  3.14999151e-02
   4.23634057e-03  4.40154827e-02  7.64294941e-02  8.08954023e-05
   4.51244463e-02 -1.99169098e-01  3.20955581e-02  8.82171828e-02
  -4.13843552e-04]
 [-4.52984553e-02  8.16593166e-02  1.08410558e-03  8.41228721e-03
  -1.24735111e-03 -6.17953349e-02 -1.25134493e-01  2.66681781e-03
  -5.53302456e-02  2.15898598e-01 -3.29587169e-02 -1.15483889e-01
  -1.06441285e-03]]
b_svc =  [-0.00381304  0.00920053 -0.00679594]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [233]:
# Define SimpleLienarClassfier here.
class SimpleLinearClassifier:
  def __init__(self,weight,bias):
    self.weight = weight
    self.bias = bias

  def probability(self,X):
    #y = X.T.dot(self.weight)+np.expand_dims(self.bias,0)[45,13] x [13,3]
    y= X.dot(self.weight.T)+np.expand_dims(self.bias,0)
    #softmax
    exp_y=np.exp(y-np.max(y))
    #print(exp_y.shape)
    sum = np.sum(exp_y,axis=1) #각 column들의 합 = Class별
    #print(sum.shape)
    #print(np.expand_dims(sum,axis=1).shape)
    return (exp_y/np.expand_dims(sum,axis=1))

  def predict(self,X):
    prob = self.probability(X)
    #highest values of column
    return np.argmax(prob,axis=1)

  def score(self, X, y):
    hats = self.predict(X)
    answer = y[hats==y]
    return len(answer)/len(y)
  


TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

In [235]:
simple_lr = SimpleLinearClassifier(W_lr,b_lr)
print('train score =',simple_lr.score(X_train,y_train))
print('test score =',simple_lr.score(X_test,y_test))

train score = 0.9924812030075187
test score = 0.9333333333333333


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

In [185]:
print('y_hat = ',simple_lr.predict(X_test))
print('y_test =',y_test)

y_hat =  [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 2 0 1 0 1 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 1 0 1 1 1]
y_test = [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

In [221]:
prob = simple_lr.probability(X_test)
print('prob =',prob)
print('The sum of rows = ',np.sum(prob,axis=1))

prob = [[9.91523974e-01 1.06809396e-03 7.40793157e-03]
 [3.77327532e-06 1.30747729e-07 9.99996096e-01]
 [3.44245206e-03 9.96346395e-01 2.11152743e-04]
 [9.84160185e-01 1.48380428e-03 1.43560112e-02]
 [3.47198262e-03 9.96246866e-01 2.81151540e-04]
 [3.24070085e-03 9.92522269e-01 4.23702975e-03]
 [9.98974254e-01 8.79461736e-05 9.37799443e-04]
 [9.33756528e-04 9.70685064e-05 9.98969175e-01]
 [7.45239054e-03 9.91861675e-01 6.85934882e-04]
 [1.77271256e-03 9.97704602e-01 5.22685383e-04]
 [8.96380394e-02 1.14086635e-02 8.98953297e-01]
 [2.34976560e-03 2.79276387e-02 9.69722596e-01]
 [9.99918361e-01 3.14178153e-07 8.13251425e-05]
 [1.98520006e-01 8.00879300e-01 6.00693636e-04]
 [3.52047348e-04 1.71638882e-05 9.99630789e-01]
 [2.14401123e-05 9.99974013e-01 4.54707456e-06]
 [9.88633382e-01 7.01422817e-04 1.06651955e-02]
 [9.99961126e-01 9.20343542e-10 3.88732006e-05]
 [8.16704638e-03 1.12844947e-01 8.78988007e-01]
 [9.99869347e-01 5.27342750e-05 7.79184901e-05]
 [1.18290976e-01 8.81018904e-01 6

TO DO: Print the accuracy on the training and test data.

In [236]:

print('train score =',simple_lr.score(X_train,y_train))
print('test score =',simple_lr.score(X_test,y_test))

train score = 0.9924812030075187
test score = 0.9333333333333333


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

In [237]:
simple_svc = SimpleLinearClassifier(W_svc,b_svc)
print('train score =',simple_svc.score(X_train,y_train))
print('test score =',simple_svc.score(X_test,y_test))

train score = 0.7518796992481203
test score = 0.8444444444444444


TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

In [240]:
print('predicted = ', simple_svc.predict(X_test))
print('y_test = ',y_test)

predicted =  [0 2 1 0 1 1 0 2 1 1 1 1 0 1 2 1 0 0 1 0 1 0 1 1 1 1 1 1 1 2 0 1 1 0 0 1 1
 1 1 2 1 0 1 1 1]
y_test =  [0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

In [239]:
prob = simple_svc.probability(X_test)
print('prob =',prob)
print('The sum of rows = ',np.sum(prob,axis=1))

prob = [[0.53293397 0.41192871 0.05513733]
 [0.0393981  0.18678317 0.77381873]
 [0.06313196 0.83833979 0.09852825]
 [0.48266953 0.45601657 0.0613139 ]
 [0.04048104 0.85363099 0.10588797]
 [0.01898321 0.88345737 0.09755942]
 [0.69831842 0.27792827 0.02375331]
 [0.08957327 0.35100437 0.55942236]
 [0.09552024 0.80580966 0.0986701 ]
 [0.08395637 0.82188882 0.09415481]
 [0.25722654 0.5132085  0.22956496]
 [0.06934112 0.49849737 0.43216151]
 [0.89385111 0.09347783 0.01267106]
 [0.16504683 0.76483735 0.07011582]
 [0.12609925 0.3851616  0.48873916]
 [0.02868094 0.90334997 0.06796909]
 [0.55356628 0.41060228 0.03583144]
 [0.96186813 0.03105956 0.00707232]
 [0.09610799 0.60996405 0.29392797]
 [0.76326632 0.21454474 0.02218894]
 [0.16086376 0.72506163 0.11407461]
 [0.56593995 0.39496929 0.03909076]
 [0.12064504 0.798698   0.08065696]
 [0.12659954 0.81236561 0.06103485]
 [0.20333638 0.68925327 0.10741034]
 [0.02698513 0.9043995  0.06861537]
 [0.03490521 0.86699924 0.09809555]
 [0.04560221 0.875820

TO DO: Print the accuracy on the training and test data.

In [238]:
print('train score =',simple_svc.score(X_train,y_train))
print('test score =',simple_svc.score(X_test,y_test))

train score = 0.7518796992481203
test score = 0.8444444444444444
